import '@/global.css'
import { AuthProvider } from "@/providers/authProviders";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<div>
       <AuthProvider>{children} </AuthProvider> 
       </div>
  );
}
